name: "Test action-amazon-chime"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1

    - run: npm ci
    - run: npm run build

    - uses: ./ # Uses an action in the root directory
      with:
        message: |
          [${{ github.workflow }}][${{ github.event_name }}] :white_check_mark: Test message sent by the action-amazon-chime e2e test.
          Link to GitHub Action run: https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks
        # Webhook URL to the chat room called "Test Room".
        webhook: ${{ secrets.testRoomWebHookUrl }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
      if: always()
      # Allow build reports to fail on pull requests.
      # When a contribution is made on a fork, the secrets will not be available,
      # and this step will be failing. This is acceptable.
      # On the other end, we want to be notified if this happens on merge, or
      # on schedule.
      continue-on-error: ${{ github.event_name == 'pull_request'}}
    - uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      if: always()
      # Allow build reports to fail on pull requests.
      # When a contribution is made on a fork, the secrets will not be available,
      # and this step will be failing. This is acceptable.
      # On the other end, we want to be notified if this happens on merge, or
      # on schedule.
      continue-on-error: ${{ github.event_name == 'pull_request'}}
